apiVersion: v1
kind: Service
metadata:
  name: omniscient
spec:
  ports:
  - port: 3000
  type: LoadBalancer
  selector:
    app: omniscient
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniscient
  labels:
    app: omniscient
spec:
  selector:
    matchLabels:
      app: omniscient
  template:
    metadata:
      labels:
        app: omniscient
    spec:
      containers:
      - name: omniscient
        image: omniscient
        ports:
        - containerPort: 3000