apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: omniscient
build:
  artifacts:
  - image: omniscient
    context: .
    docker:
      dockerfile: ./py/Dockerfile
deploy:
  kustomize:
    paths:
    - ./manifests/overlays/dev
profiles:
- name: prod
  deploy:
    kustomize:
      paths:
      - ./manifests/overlays/prod
- name: staging
  deploy:
    kustomize:
      paths:
      - ./manifests/overlays/staging
